use anyhow::{Context, Result};
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};
use tempfile::tempdir;
use ugoite_iceberg::{audit, service::UgoiteService};

const FIXTURE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/historical-spaces/v0.2.0-audit-reconciliation"
);
const SPACE_ID: &str = "01a0f519-e7e8-755c-8bba-c57aae4b9f64";
const PRINCIPAL_ID: &str = "34180000-0000-4000-8000-000000000001";
const ENTRY_EVENT_ID: &str = "39867b82-5b71-50d3-a26c-fea0e62e43a8";
const SQL_EVENT_ID: &str = "6caef060-ddd8-538a-9214-d20d7857b900";
const ENTRY_EVENT_HASH: &str = "efc60721dc0ca0bd5865209e55004f2682f71f42e2131dbde122570267236633";
const SQL_EVENT_HASH: &str = "488c4e77936c554e823e180695ad6f92e533362be00816a737835332569585ee";
const EVENTS_FILE_SHA256: &str = "3537f8a629361f28a515d8e7ca04163c9bf1b2a3e9793eaaf898789ee8567147";

fn copy_tree(source: &Path, destination: &Path) -> Result<()> {
    fs::create_dir_all(destination)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let destination_path = destination.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_tree(&source_path, &destination_path)?;
        } else {
            fs::copy(&source_path, &destination_path)?;
        }
    }
    Ok(())
}

fn verify_frozen_manifest(fixture: &Path) -> Result<()> {
    let manifest = fs::read_to_string(fixture.join("SHA256SUMS"))?;
    for line in manifest.lines().filter(|line| !line.trim().is_empty()) {
        let (expected, relative_path) = line
            .split_once("  ")
            .context("SHA256SUMS entry must use two spaces")?;
        let bytes = fs::read(fixture.join(relative_path))?;
        let actual = hex::encode(Sha256::digest(&bytes));
        assert_eq!(
            actual, expected,
            "frozen fixture file changed: {relative_path}"
        );
    }
    Ok(())
}

fn event_bytes(root: &Path) -> Result<Vec<u8>> {
    Ok(fs::read(
        root.join("spaces")
            .join(SPACE_ID)
            .join("audit/events.jsonl"),
    )?)
}

/// The persisted attribution variations were generated by the released
/// v0.2.0 source, not projected by the current writer. Opening the Space must
/// retain those verified events byte-for-byte.
#[tokio::test]
async fn v020_audit_events_remain_unchanged_on_open_and_reconcile() -> Result<()> {
    let fixture = PathBuf::from(FIXTURE_DIR);
    verify_frozen_manifest(&fixture)?;
    let temp_root = tempdir()?;
    copy_tree(&fixture, temp_root.path())?;

    let event_path = temp_root
        .path()
        .join("spaces")
        .join(SPACE_ID)
        .join("audit/events.jsonl");
    let events_before = event_bytes(temp_root.path())?;
    assert_eq!(
        hex::encode(Sha256::digest(&events_before)),
        EVENTS_FILE_SHA256,
        "v0.2.0 audit fixture is immutable evidence"
    );
    let events: Vec<Value> = std::str::from_utf8(&events_before)?
        .lines()
        .map(serde_json::from_str)
        .collect::<std::result::Result<_, _>>()?;
    assert_eq!(events.len(), 2);
    assert_eq!(events[0]["event_id"], ENTRY_EVENT_ID);
    assert_eq!(events[0]["subject_principal_id"], PRINCIPAL_ID);
    assert_eq!(events[0]["actor_principal_id"], PRINCIPAL_ID);
    assert_eq!(events[0]["prev_hash"], "root");
    assert_eq!(events[0]["event_hash"], ENTRY_EVENT_HASH);
    assert_eq!(events[1]["event_id"], SQL_EVENT_ID);
    assert_eq!(events[1]["subject_principal_id"], PRINCIPAL_ID);
    assert!(events[1]["actor_principal_id"].is_null());
    assert_eq!(events[1]["prev_hash"], ENTRY_EVENT_HASH);
    assert_eq!(events[1]["event_hash"], SQL_EVENT_HASH);

    let meta_path = temp_root
        .path()
        .join("spaces")
        .join(SPACE_ID)
        .join("meta.json");
    let meta_before = fs::read(&meta_path)?;
    let entry_marker = temp_root
        .path()
        .join("spaces")
        .join(SPACE_ID)
        .join("audit/event-ids")
        .join(format!("{ENTRY_EVENT_ID}.json"));
    let sql_marker = temp_root
        .path()
        .join("spaces")
        .join(SPACE_ID)
        .join("audit/event-ids")
        .join(format!("{SQL_EVENT_ID}.json"));
    let markers_before = [fs::read(&entry_marker)?, fs::read(&sql_marker)?];

    let root_uri = format!("file://{}", temp_root.path().display());
    let service = UgoiteService::new_without_background_refresh(&root_uri)?;
    let history_before = service.entry_history(SPACE_ID, "fixture-entry").await?;
    let sql_before = service.get_saved_sql(SPACE_ID, "fixture-query").await?;

    service.open_space(SPACE_ID).await?;
    assert_eq!(
        service.get_entry(SPACE_ID, "fixture-entry").await?["id"],
        "fixture-entry"
    );
    assert_eq!(
        service.entry_history(SPACE_ID, "fixture-entry").await?,
        history_before
    );
    assert_eq!(
        service.get_saved_sql(SPACE_ID, "fixture-query").await?,
        sql_before
    );
    let listed = service.list_space_audit(SPACE_ID, 0, 100).await?;
    assert_eq!(listed["total"], 2);
    assert_eq!(
        audit::verify_integrity(service.operator(), SPACE_ID).await?,
        2
    );

    let items = listed["items"]
        .as_array()
        .context("audit list has no items")?;
    let persisted_entry = items
        .iter()
        .find(|event| event["event_id"] == ENTRY_EVENT_ID)
        .context("v0.2.0 Entry event is missing")?;
    let persisted_sql = items
        .iter()
        .find(|event| event["event_id"] == SQL_EVENT_ID)
        .context("v0.2.0 Saved SQL event is missing")?;
    assert_eq!(persisted_entry["actor_principal_id"], PRINCIPAL_ID);
    assert!(persisted_sql["actor_principal_id"].is_null());

    service
        .reconcile_entry_audit(SPACE_ID, "fixture-entry", &[], "ignored")
        .await?;
    service
        .reconcile_saved_sql_audit(SPACE_ID, "fixture-query", &[], "ignored")
        .await?;
    service.open_space(SPACE_ID).await?;

    assert_eq!(event_bytes(temp_root.path())?, events_before);
    assert_eq!(fs::read(&meta_path)?, meta_before);
    assert_eq!(fs::read(&entry_marker)?, markers_before[0]);
    assert_eq!(fs::read(&sql_marker)?, markers_before[1]);
    assert!(event_path.exists());
    Ok(())
}
